# tasks file for artifactory
---
- name: install java 11
  yum:
    name: java-11-openjdk-devel
    state: present
- name: Add Artifactory Yum Repository
  yum_repository:
    name: jfrog-artifactory
    description: JFrog Artifactory RPM Repository
    baseurl: https://releases.jfrog.io/artifactory/artifactory-rpms
    gpgcheck: yes
    gpgkey: https://releases.jfrog.io/artifactory/api/gpg/key/public
    enabled: yes
- name: Update Yum Cache and Install Artifactory
  yum:
    name:
      - jfrog-artifactory-oss
    state: present
    update_cache: yes
- name: Start and Enable Artifactory
  service:
    name: artifactory
    state: started
    enabled: yes







